require('events').EventEmitter.prototype._maxListeners = 100;
const http = require("http");
const https = require('https');
const csv2json_f = require('csv2json');
const fs = require('fs');
const trim = require('trim');
const cheer = require('cheerio');
const $r = require('request');
const $j = $r.jar();
const Mongo = require('mongodb').MongoClient;
const mongojs = require('mongojs');
const s4 = require('./apps/getSX4sList.js').s4;
s4.init();